### ISSUE TITLE
Remove a Company

### ISSUE THREAD

**Issue by HarPlay** [bradwestfall/webdevphoenix#106]
Hello, I need to remove "G/O Digital" as they're becoming their parent company TEGNA and possibly no longer hiring developers in Phoenix.  There were great directions when I set them up and I cannot find them now, nor know enough to infer what to do.  Thank you!

**Comment by bradwestfall** [comment]
Done, thanks Rachel

**Comment by HarPlay** [comment]
Fantastic, thanks Brad!
